# build.yaml
targets:
  super_model:
    sources:
      include:
        - lib/**
        - test/**       # Include test directory
    builders:
      dart_mappable:    # The builder from the dart_mappable package
        generate_for:
          - lib/**.dart
          - test/**.dart
