name: super_model
description: A new Dart package for model handling using Dart macros
version: 0.0.1
homepage: https://github.com/yourusername/super_model
publish_to: none  # Remove this line when publishing to pub.dev

environment:
  sdk: '>=3.6.0-0 <4.0.0'

dependencies:
  dart_mappable: ^4.3.0

dev_dependencies:
  macros: ^0.1.3-main.0
  lints: ^5.1.1
  build_runner: ^2.4.0
  dart_mappable_builder: ^4.3.0
  test: ^1.24.0
