name: super_model
description: Base class, annotations and utilities for data models with reflection and relationships
version: 0.1.0
homepage: https://github.com/yourusername/super_model
publish_to: none  # Remove this line when publishing to pub.dev

environment:
  sdk: ">=3.6.0-0 <4.0.0"

dependencies:
  dart_mappable: ^4.5.0
  source_gen: ^2.0.0
  build: ^2.4.2
  analyzer: ^7.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
