name: super_model
description: A new Dart package for model handling using code generation
version: 0.0.1
homepage: https://github.com/yourusername/super_model
publish_to: none  # Remove this line when publishing to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_mappable: ^4.3.0
  source_gen: ^1.4.0
  build: ^2.4.1
  analyzer: ^6.2.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
